== Summary

NiMMbus (+++<a href="https://www.nimmbus.cat/" target="_blank">https://www.nimmbus.cat</a>+++) is a solution for storing geospatial resources on the MiraMon cloud. Several resources can be stored in NiMMbus: points of interest, hyperlinks to a geospatial databases, citations of geospatial resources, publications and feedback items.

For the latter, the system implements the Geospatial User Feedback standard (+++<a href="http://www.opengeospatial.org/standards/guf" target="_blank">http://www.opengeospatial.org/standards/guf</a>+++) originated in the EU FP7 GeoViQua project. It allows to provide comments, ratings, questions, etc that can be associated with geospatial assets on a catalogue using a data/metadata identifier. The contribution of the H2020 NextGEOSS project is to extend the initial implementation of NiMMbus to support GUF resources. The system allows for creating a citation of an external resource (pointing to a external catalogue or repository) and associate feedback items to it.

More information on NiMMbus can be found in +++<a href="https://github.com/joanma747/nimmbus" target="_blank">NiMMbus GitHub</a>+++.
//nimmbus mm cloud, incloent citations i guf...

//origen MM i nextgeooss

=== Acknowledgements

The NextGEOSS project has received funding from the European Union Horizon 2020 research and innovation programme under grant agreement No 730329.
This documentation and implementation reflects only the author's view and the Agency is not
responsible for any use that may be made of the information it contains.

===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:

.Contacts
[width="80%",options="header",caption=""]
|====================
|Name |Organization
|Alaitz Zabala | UAB
|Joan Masó | CREAF
|====================
