[[Resources]]
== *Resources*

As *NiMMbus is a repository for saving and sharing geospatial information*, there are five types of resources to be created, depending on the characteristics of the information that needs to be saved to describe the resource. The five types of resources are briefly described in the next sub-sections. and fully described in a section for each.

Further more, *one of NiMMbus's main goals is to generate and improve knowledge from metadata and interaction between users*. For that, there is the option of creating a new resource that can only be viewed by the owner, to share it with a specific person/organization (using a NiMMbus user name or an e-mail), or to share it with the NiMMbus community. To define that property, there is a small box at the end of each resource page to mark/unmark for making it visible to other users. For sharing resources with other users of NiMMbus, search for it at the general resources page, and press on "_Share_" bottom.

[[Res_feedback_item]]
=== *Feedback item*
Creating feedback is providing information or opinions about a geospatial resource, on base of the experience of users with it. In that way, it is also a *key driver to improve data information*, as to make and transmit knowledge about data of experience using data.

The goal is to *inform other users about the experience using a specific resource* (for example: how, when and why it was used in a particular way, a comment about the experience using it or an opinion about it). So that, other users can consider that assessment when it is needed and even the provider can improve the product after reading this feedback item. In that way, feedbacks are helping us on improving datasets as well as creating knowledge from metadata.

+++<a href="#Feedback">Feedback</a>+++ section explains in detail all the elements about the GUF item (look for more details there).

[[Res_responsible_party]]
=== *Responsible party: Individual & Organization*
This section is for making an *identification file of a single person or an organization that has created a resource*.

In the case of creating the description for an individual, it contains: the role, name, contact and position of the person. When it comes to an organization, the required data is: the name and some address data, such as the city, postal code, country, among others.

This resource is typically used within a feedback item (to identify the user creating the feedback item) or within a citation or publication (to identify parties related to the citation such as the editor, author, funder…).

[[Res_hyperlink]]
=== *Hyperlink*
This section is for creating a *link to an online resource of interest*, such as a website with shapefiles or satellite images, for example.

To create this type of resource some characteristics shall be defined, as the title, the URL, the format of the resource (MMZ, MMZX, ZIP, JPEG, PNG, or others -to define-), and a brief explanation of the motivations to save this resource.

[[Res_PoI]]
=== *Point of interest*
The main goal is to be able to *pinpoint a single point feature with an exact location* (with coordinates), so that features or phenomena can be accurately located (for example at a single pixel or group of pixels).

To create this type of resource, the following properties need to be specified: a title, the coordinates (that can be directly obtained from the device if location services are active), and a small note with the motivation of this resource.

[[Res_Cit_Pub]]
=== *Citation & Publication*
This type of resource is a resource reference, associated to the *set of bibliographic characteristics of a file*, so that it’s defined as the information object containing information that directs a user’s attention from one resource to another.

The information needed to create a citation is: the title or name of the resource, the creating date, a unique identification code, information about the person responsible for the resource (that could be an individual or an organization), information about the serial number of the resource (name, ID, and pages) and also about the online resource (URL, URL description). The publication resource extends the citation so it allows to also define a summary and a category describing the type of publication (e.g. book chapter, journal article, webpage…).

These resources are typically used within a feedback item. 

+++<a href="#Citation">Citation</a>+++ & +++<a href="#Publication">Publication</a>+++ sections explains in detail all the elements about the Citation & Publication items respectively (look for more details there).

